[theme]
base = "dark"
primaryColor = "#00D2FF"
backgroundColor = "#011A24"
secondaryBackgroundColor = "#032B3A"
textColor = "#F1F5F9"

[server]
headless = true
runOnSave = true
address = "0.0.0.0"
port = 8501
enableCORS = false
enableXsrfProtection = false

# Configuración pensada para uso en tableta Android vía navegador
[browser]
gatherUsageStats = false
